export { C, FONTS_URL } from "./theme";
export {
  NAV_LINKS,
  SOCIAL_LINKS,
  STATS,
  SKILL_CATEGORIES,
  EXPERIENCES,
  EDUCATION_OVERVIEW,
  COURSEWORK,
  ACTIVITIES,
  PROJECTS,
} from "./data";
